[package]
name = "kbe_seed_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
kaspa-bip32 = { git = "https://github.com/wigwagwent/rusty-kaspa", rev = "b8ea20b7" }
kbe_utils = { path = "../kbe_utils" }

[dev-dependencies]
hex = "0.4"