[package]
name = "send_kaspa_transaction"
version = "0.1.0"
edition = "2024"

[dependencies]
kaspa-addresses = "0.15"
kaspa-bip32 = "0.15"
kaspa-wallet-core = "0.15"
tokio = { version = "1", features = ["full"] }
kaspa-wrpc-client = "0.15"
dotenv = "0.15.0"